import { Medication, PharmacyProduct, User } from '../types';

export const MOCK_USER: User = {
  id: 'user-1',
  name: 'João Silva',
  email: 'joao.silva@email.com',
  phone: '(11) 99999-9999',
  address: 'Rua das Flores, 123, São Paulo - SP',
  createdAt: new Date().toISOString(),
};

export const MOCK_MEDICATIONS: Medication[] = [
  {
    id: 'med-1',
    name: 'Losartana',
    dosage: '50mg',
    form: 'Comprimido',
    frequency: 'daily',
    times: ['08:00'],
    stock: 28,
    lowStockThreshold: 5,
    instructions: 'Tomar com água, preferencialmente pela manhã.',
    startDate: new Date().toISOString(),
    active: true,
  },
  {
    id: 'med-2',
    name: 'Metformina',
    dosage: '850mg',
    form: 'Comprimido',
    frequency: 'daily',
    times: ['12:00', '20:00'],
    stock: 56,
    lowStockThreshold: 10,
    instructions: 'Tomar junto com as refeições.',
    startDate: new Date().toISOString(),
    active: true,
  },
  {
    id: 'med-3',
    name: 'Dipirona',
    dosage: '500mg',
    form: 'Comprimido',
    frequency: 'as_needed',
    times: [],
    stock: 10,
    lowStockThreshold: 3,
    instructions: 'Tomar em caso de dor ou febre.',
    startDate: new Date().toISOString(),
    active: true,
  },
];

export const MOCK_PHARMACY_PRODUCTS: PharmacyProduct[] = [
  {
    id: 'prod-1',
    name: 'Vitamina C 1g',
    description: 'Suplemento vitamínico antioxidante. Auxilia no funcionamento do sistema imune.',
    price: 15.90,
    category: 'Vitaminas',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-2',
    name: 'Paracetamol 750mg',
    description: 'Analgésico e antitérmico indicado para redução da febre e alívio temporário de dores leves a moderadas.',
    price: 8.50,
    category: 'Dor e Febre',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-3',
    name: 'Ômega 3 1000mg',
    description: 'Suplemento alimentar de óleo de peixe em cápsulas.',
    price: 45.00,
    category: 'Suplementos',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-4',
    name: 'Protetor Solar FPS 50',
    description: 'Alta proteção contra raios UVA e UVB. Toque seco.',
    price: 69.90,
    category: 'Cuidados Pessoais',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-5',
    name: 'Xarope para Tosse',
    description: 'Expectorante e calmante da tosse.',
    price: 22.30,
    category: 'Gripe e Resfriado',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-6',
    name: 'Atenolol 25mg',
    description: 'Indicado para o controle da hipertensão arterial (pressão alta).',
    price: 12.50,
    category: 'Hipertensão',
    inStock: true,
    requiresPrescription: true,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-7',
    name: 'Omeprazol 20mg',
    description: 'Indicado para tratar úlceras gástricas e refluxo.',
    price: 18.90,
    category: 'Estômago',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-8',
    name: 'Levotiroxina Sódica 50mcg',
    description: 'Reposição ou suplementação de hormônios da tireoide.',
    price: 14.20,
    category: 'Tireoide',
    inStock: true,
    requiresPrescription: true,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-9',
    name: 'Loratadina 10mg',
    description: 'Antialérgico para alívio dos sintomas de rinite alérgica.',
    price: 9.90,
    category: 'Alergia',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-10',
    name: 'Amoxicilina 500mg',
    description: 'Antibiótico usado no tratamento de diversas infecções bacterianas.',
    price: 25.50,
    category: 'Antibióticos',
    inStock: true,
    requiresPrescription: true,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-11',
    name: 'Ibuprofeno 600mg',
    description: 'Anti-inflamatório, analgésico e antitérmico.',
    price: 16.80,
    category: 'Dor e Inflamação',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-12',
    name: 'Simeticona 125mg',
    description: 'Alívio do desconforto abdominal, aumento de volume abdominal, dor ou cólicas causadas por gases.',
    price: 11.00,
    category: 'Estômago',
    inStock: true,
    requiresPrescription: false,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-13',
    name: 'Losartana Potássica 50mg',
    description: 'Indicado para o tratamento da hipertensão arterial.',
    price: 8.90,
    category: 'Hipertensão',
    inStock: true,
    requiresPrescription: true,
    imageUrl: 'https://via.placeholder.com/150',
  },
  {
    id: 'prod-14',
    name: 'Metformina 850mg',
    description: 'Antidiabético oral para tratamento do diabetes tipo 2.',
    price: 10.50,
    category: 'Diabetes',
    inStock: true,
    requiresPrescription: true,
    imageUrl: 'https://via.placeholder.com/150',
  },
];
